### ISSUE TITLE
Flex 界面设计

### ISSUE THREAD

**Issue by sgjsakura** [ZJU-CC98/Forum#1]
包含如下列表：
1. 首页
2. 版面列表
3. 版面内容
4. 登录
5. 注册
6. 发主题
7. 个人中心
8. 关注
9. 新帖
10. 浏览帖子
11. 我的粉丝
12. 我的关注
13. 我的设置
14. 我的收藏
15. 我的私信
16. 我的主题

请大家回复认领任务并为每个任务单独开 Issue，谢谢！

**Comment by Dearkano** [comment]
领
2.版面列表
3.版面内容
4.登录
5.注册

**Comment by Dearkano** [comment]
领 
帖子类

6.发主题
9.新帖
10.浏览帖子

**Comment by Dearkano** [comment]
领 
帖子类
3.版面内容
6.发主题
10.浏览帖子

**Comment by AsukaSong** [comment]
7.个人中心
11.我的粉丝
12.我的关注

另求个队友一起弄个人中心类 _(:з)∠)_

**Comment by RiotChen** [comment]
个人中心类
13、我的设置
14、我的收藏
16、我的主题

**Comment by mingyigg** [comment]
帖子类
3.版面内容
8.关注
9.新帖

**Comment by adddna** [comment]
首页类
1.首页
2.版面列表

**Comment by adddna** [comment]
好久没人推了……前辈们加油啊QAQ

**Comment by adddna** [comment]
又一周过去了……依然进展缓慢orz……
