### ISSUE TITLE
纯内网环境上不去，建议把前端相关文件全搞成内网的

### ISSUE THREAD

**Issue by XiangTianxiao** [ZJU-CC98/Forum#10]
纯内网环境下无法显示页面，curl看一下，发现了不少cdn.bootcss.com的链接，建议替换为内网的。内网bug楼根本打不开，没有办法反馈

**Comment by cians** [comment]
直接下载到内网，然后链接导向内网吧

**Comment by sgjsakura** [comment]
前辈你好，感谢你的反馈。

目前论坛第三方库都是具有回退设置的，网站首先会尝试连接CDN，下载失败之后会转而使用网站自带的版本。之所以这么设置，主要是希望利用CDN降低98的流量压力嗯。不过由于浏览器判断下载失败的过程不受控制，判断时间可能会较长（在网络不稳定的情况下甚至可能要半分钟或者更久才会被迫使用回退），因此可能实际效果不是很理想。

这个问题我们后续将做进一步考虑，如果有任何进展也会在这里公布~

**Comment by AsukaSong** [comment]
794d5a6639171196f1ed22337afbc5db5775d0d2

所有的相关文件都已经改到内网了
