### ISSUE TITLE
[提问] 请问新版论坛对老账号有修改吗？

### ISSUE THREAD

**Issue by WYXF007** [ZJU-CC98/Forum#12]
你好，我是已经毕业的水沟，没事通过 rvpn 回来水水，但是不知道为啥，我的账户似乎失效了。。。输入用户名密码显示密码错误，我已经试过所有以前用过的密码了。请问新版论坛是将通行证失效的账户删除了吗？

**Comment by Tsukiko15** [comment]
没删除老帐号，可能是你忘记密码了

**Comment by AsukaSong** [comment]
https://account.cc98.org/
