### ISSUE TITLE
帖子列表的div的id全都一样

### ISSUE THREAD

**Issue by yujincheng08** [ZJU-CC98/Forum#14]
都是`id="changeColor"`，应该改成`class`比较好
![tim 20180102111641](https://user-images.githubusercontent.com/5022927/34473501-816bedac-efae-11e7-87d9-6c7d43503521.png)

**Comment by AsukaSong** [comment]
会在下个版本修复

**Comment by Dearkano** [comment]
余。。余神orz

**Comment by yujincheng08** [comment]
大大大佬您是？？

**Comment by yujincheng08** [comment]
修了为什么不关ISSUE啦
