### ISSUE TITLE
在关注列表多次点击版面名会反复切换版面

### ISSUE THREAD

**Issue by AsukaSong** [ZJU-CC98/Forum#30]
[关注版面](http://www.cc98.org/focus)

具体来说，例如我关注了动漫讨论版，进入这个页面第一次点击动漫讨论会切过去，再次点击又会切回全部帖子。

**Comment by AsukaSong** [comment]
@mingyigg

**Comment by mingyigg** [comment]
这不算bug吧，当初就是这么设计来着， 点击了动漫讨论是切换到这个版面，再次点击就是取消关注这个版面了
