### ISSUE TITLE
引用层级太深/多重引用 问题

### ISSUE THREAD

**Issue by Deturium** [ZJU-CC98/Forum#31]
考虑重新写一下对应样式，或者对过深的引用做特殊处理

![image](https://user-images.githubusercontent.com/19731097/34659902-0542172c-f479-11e7-8ff6-68aa1507e6bc.png)

**Comment by mingyigg** [comment]
不是说折叠起来么，跟A站一样

**Comment by AsukaSong** [comment]
fd6632ccd7424ce1c29901eb2c0f9df49ea22e66

调整了一下边距

![qq 20180201162946](https://user-images.githubusercontent.com/26486891/35668618-21deb9ba-076d-11e8-80a8-e31126f281de.png)

**Comment by AsukaSong** [comment]
8fc1fefd43f482bb137d370f61bb47159839f389
ed6a9a695c3f271c70212532dbf59d286fc04761

重写了引用的样式，并对大于两层的引用添加了自动折叠

<img width="852" alt="2018-05-03 10 46 56" src="https://user-images.githubusercontent.com/26486891/39558230-70175170-4ebf-11e8-9ddc-91c6819d291f.png">

**Comment by Deturium** [comment]
重写了 QuoteTagHandler， [commit #ec8843](https://github.com/ZJU-CC98/Forum/commit/ec388436025c6c0f43ba792a83994aca50ab811d)
通过 flat 嵌套的 [quote] 解决之前 AsukaSong 使用 css hack 导致的问题
