### ISSUE TITLE
上传文件时检查后缀及添加audio、video标签解析

### ISSUE THREAD

**Issue by adddna** [ZJU-CC98/Forum#33]
如题，根据主席要求，上传文件时检测后缀名，图片使用img标签，音频使用audio标签，视频使用video标签，其他使用upload标签，并添加与隐藏图片相同的样式。
另外需要实现audio与video标签的解析。

**Comment by AsukaSong** [comment]
检测做好发布在test上了。是根据MIME type检测的。

**Comment by AsukaSong** [comment]
1b649fe32e6ca66e45e1e7073e9b761efd86616a 
添加了对audio标签的解析
已经发布在test上了

**Comment by AsukaSong** [comment]
3e5a2480b900746d28dd5025311f68d9417453c1
添加了对video的解析，发布在test

**Comment by AsukaSong** [comment]
a7d1cede0ce652635c1f19cce0357b4002a9a0fb
添加了后缀名识别以及修复了一些BUG
所有改动已经正式发布，关掉了
