### ISSUE TITLE
getTagTopics 函数存在Bug

### ISSUE THREAD

**Issue by mwindson** [ZJU-CC98/Forum#46]
1. 54 行应该改成 **query += `tag2=${tag2}&`;** 

2. 如果选择器选择 **全部** ，传入的tagId是`"-1"`，是字符串类型，必然不完全等于`-1`。考虑进行类型转换或者使用`!=`

https://github.com/ZJU-CC98/Forum/blob/431c64b499f96eb6c7623d864ce11d2009cecaa9/CC98.Forum/CC98.Forum/Pages/Board/action.ts#L42-L58

**Comment by Dearkano** [comment]
Thanks 已修复
