### ISSUE TITLE
帖子与版面需要的API

### ISSUE THREAD

**Issue by Dearkano** [ZJU-CC98/Forum#7]
返回某帖子的数组信息时，添加
1.粉丝数
2.点赞、踩数、评论数
3.评分及评价、打赏

需要一个能追踪某一个用户的发言的API

需要增加评分打赏及评论功能

需要一个新API作为鼠标hover时弹出的页面
返回帖数、勋章、职务

**Comment by Dearkano** [comment]
需要添加搜索API 搜索有几种TAG

**Comment by Dearkano** [comment]
帖子列表的需要的API
1.返回帖子数组时同时返回点赞、踩、评论数
2.编辑版面公告的功能
3.标签功能，包括创建、删除标签。根据标签返回特定内容

**Comment by Dearkano** [comment]
投票部分的API
现在这部分没有任何API ，都需要重做

**Comment by Dearkano** [comment]
匿名板块的ID以及头像问题

**Comment by 6769** [comment]
by the way, 新版本api的接口文档什么时候出啊
