### ISSUE TITLE
head里的title标签是空的，导致了浏览器的标签页显示的是网址

### ISSUE THREAD

**Issue by awmleer** [ZJU-CC98/Forum#9]
![image](https://user-images.githubusercontent.com/16526078/34240253-8de07c76-e647-11e7-8cee-3cc2cda3e881.png)

![image](https://user-images.githubusercontent.com/16526078/34240258-93ee59d0-e647-11e7-9cc9-07d07b140352.png)

**Comment by sgjsakura** [comment]
HI，前辈你好，感谢你的反馈，这个问题我们已经做了一定的修复，目前标题栏已经会显示论坛名称，在近期的更新中我们还会加上每个页面的标题~

如果前辈还有其他意见建议，欢迎随时反馈~这个Issue已经在我们的计划内，因此就先关闭了~
